services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: barbershopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - barbershop-net

  app:
    build: .
    container_name: barbershop-app
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/barbershopdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - barbershop-net

volumes:
  pgdata:

networks:
  barbershop-net:
